services:
  - type: web
    name: ai-calendar-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn simple_app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG_ENDPOINTS
        value: true 